name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
env:
  MY_VAR: "Hello World"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-python:latest
        
      - name: Var Print    
        run: |
          echo "Build Number: ${{ github.event.pull_request.number }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Branch Name: ${{ github.ref }}"
          echo "Repository Name: ${{ github.repository }}"
          echo "Repository Owner: ${{ github.repository_owner }}"
          echo "Repository URL: ${{ github.repository_url }}"
          echo "Repository Path: ${{ github.repository_path }}"
          echo "First Style: $MY_VAR"
          echo "Second Style: ${{ env.MY_VAR }}"
          pwd
          ls -l
         
          
        
